removed usage of get_menu_dict
juntagrico/juntagrico-billing pull request #11
Opened 2021-02-15 21:55 UTC by samuel-iseli

changed billing code to be compatible with #375.

2021-02-21 15:56 UTC, motu55 requested changes
du hast noch die alten messages drin
die gehen neu so

messages = getattr(request, 'member_messages', []) or []
    messages.extend(home_messages(request))
    
   Da ich nicht auf der zeile kommentieren kann es ist 68/69 im views.py

2021-02-27 13:51 UTC, samuel-iseli commented
Warum das `or` in `messages = getattr(request, 'member_messages', []) or []`?
`messages = getattr(request, 'member_messages', [])` würde doch reichen.

2021-02-27 15:09 UTC, motu55 commented
falls das attribute aus irgendeinem grund mit None befüllt wurde wird da ein or gemacht
`>>> class Foo(object):
...     pass
...
>>> obj = Foo()
>>> getattr(obj,'bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Foo' object has no attribute 'bar'
>>> obj.bar=None
>>> print(getattr(obj,'bar'))
None
>>> print(getattr(obj,'bar',[]))
None
>>> print(getattr(obj,'bar',[]) or [])
[]`

2021-02-27 15:11 UTC, motu55 approved these changes
can be merged once the corresponding pullrequest is merged in the core project

2021-03-16 10:27 UTC, merged