Fix domain for juntagrico 1.5
juntagrico/juntagrico-billing pull request #21
Opened 2022-02-17 21:48 UTC by nixnuex

2022-02-18 07:38 UTC, samuel-iseli requested changes
I would include protocol in serverUrl. The change in the text template isn't needed then. Otherwise the translations would need to be adapted too.

2022-02-18 19:37 UTC, nixnuex commented
Done

2022-02-20 16:03 UTC, samuel-iseli requested changes

2022-02-20 16:03 UTC, samuel-iseli commented on juntagrico_billing/mailer.py
> +        'serverurl': 'https' + Site.objects.get_current().domain
Isn't the `://` missing now? 
Should be `'https://' + Site.objects.get_current().domain` to yield the same result as before.

2022-02-20 19:38 UTC, nixnuex commented
Sorry, sure.

2022-02-22 08:45 UTC, samuel-iseli approved these changes

2022-04-19 07:00 UTC, nixnuex commented
Obsolete

2022-04-19 07:00 UTC, closed without merging